[project]
name = "audiolink"
version = "0.1.0"
description = "PipeWire desktop router and media streamer"
requires-python = ">=3.14"
dependencies = [
    "pyqt6>=6.10.2",
]

[project.scripts]
audiolink = "main:main"
